---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgA4bQMZrSwc2WXUme2jiwDFZUqpX/2W6QQAkNS30nH7/V6+cRqXDvyQqYpbSgEUfHDqvu3V37dtdbplU64BvoIdTCWJkU8TX2c0as5+qvaJzVfzlj3L+blooxL/Dd3RBlcQr/+bS3pV1T6ChAK0R//jgGDENeIddeOI2DV4emJz/1olW9zsm/rFWRvfBLXZu8kcExctTIU+01xcqaLogLqfUt+2+Ic5Balgkfb0gct78yy9Lui7y4DJsCDXsik+yXelPpWITxc66ltz5H3i0TkSVtFiSxQAssnNPo9OsaSwhObhD5UfkfHVIEEjhGMIMoaJFgCpS+66NpjyttbGnxLP5DBhBEyi2+zbnt07y7cMuPbl8d7wTYe58mxloeYF6LIwSny4bqCu8n3+Ex7N7QbAG06D0UnZt/kLlqMUh5oeFUA0m51Gyjny/pj+MYPqQzfsyfWNj+cYBoO6xLdUsSOmOED2h0SpPuDX9b9Hv1nQZ7q332BRh+xk7yNPrpoWwhTUX1VWR2kx6nXJCcIETTpdYtMRlATMhx+LeibjcQ7xcMqUVSS6VB0naAFFL8wuBT+pXhFktvv77WnTh+NTslVResUKHfBUwxgjV9AegrO0Mq0QHnZYWEHj9Lf+iF2GSbTT9YGQu0O0DnpKUXGpktoTnmxDD6AC14YwVnbYY2gvzj6bQZJFiywpIwPGroTd0dXJDYwz9w==
    KEYCLOAK_CLIENT_SECRET: AgCA0/CWp2c6hIIzRD6MKRgF8wxU8AVVyWEi5aw8eUhtRbu5Tyw9pQtnMH5QCnr+PZn8PJPytDdnusNshlOJEpKtk4RbuKEsUX2rwWmaNGsvXYVka95XKrlTM+DtX7zPHglp/5MdWYbPS90vChs6W0IAaSRyfCpYm1YPEwfsshlrxtOTSnhcucou/qw6vgtEAcrwmg/29ghXxggKOoDJ1UqVNiel7bzunvfS4VDvzyMQv9BD1j4FobMjXaIHOgTTJlrzRyn77QJJXHnzgRJH1XeRJ/AdzJEwg5ecTc6TRLeP1zMuUpajYvicAW/ttYZGFzVrsKYBuzkWLCso08xTtEZrAMh4IKsA9ayXbTqIV6Cz0M/pEE1XtZJ+4F7wcJ94h0ssEpiF8aFVsnfKMzzadvs3XtzS3se/os6kaZi0w7KS8BbdvbCPOSlu4UFSsQ3J7afiShrsk+0p3UdgTsBYBFygn8gK4ISjDcTDBc0VwCj4Do0DMV9yHfDps4rH8DpcdgwjuTHfRF6zVQLdmZ2F5iK8FI9FUm+IqU4oheJFfxNQ7UFTFmoMBYrfvnJk5R0siHlEH7NM3zkn1TGGJgPTQBKRN2N92aHOpqb3hGRTSujYA0f02Khh6khYokcrW1Ep49neG7OZhrhK06kX0cuK3VPLLjyUj4nvRnsq5/4qi1jemIasSmSQpWcvwf+B5dkOb381w4a8q7AE4shL01fmSEJhblIILMJTp2pgELDFlbluTw==
  template:
    metadata:
      name: auth-service-credentials
      namespace: recruitment
    type: Opaque
