---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgA4bQMZrSwc2WXUme2jiwDFZUqpX/2W6QQAkNS30nH7/V6+cRqXDvyQqYpbSgEUfHDqvu3V37dtdbplU64BvoIdTCWJkU8TX2c0as5+qvaJzVfzlj3L+blooxL/Dd3RBlcQr/+bS3pV1T6ChAK0R//jgGDENeIddeOI2DV4emJz/1olW9zsm/rFWRvfBLXZu8kcExctTIU+01xcqaLogLqfUt+2+Ic5Balgkfb0gct78yy9Lui7y4DJsCDXsik+yXelPpWITxc66ltz5H3i0TkSVtFiSxQAssnNPo9OsaSwhObhD5UfkfHVIEEjhGMIMoaJFgCpS+66NpjyttbGnxLP5DBhBEyi2+zbnt07y7cMuPbl8d7wTYe58mxloeYF6LIwSny4bqCu8n3+Ex7N7QbAG06D0UnZt/kLlqMUh5oeFUA0m51Gyjny/pj+MYPqQzfsyfWNj+cYBoO6xLdUsSOmOED2h0SpPuDX9b9Hv1nQZ7q332BRh+xk7yNPrpoWwhTUX1VWR2kx6nXJCcIETTpdYtMRlATMhx+LeibjcQ7xcMqUVSS6VB0naAFFL8wuBT+pXhFktvv77WnTh+NTslVResUKHfBUwxgjV9AegrO0Mq0QHnZYWEHj9Lf+iF2GSbTT9YGQu0O0DnpKUXGpktoTnmxDD6AC14YwVnbYY2gvzj6bQZJFiywpIwPGroTd0dXJDYwz9w==
    KEYCLOAK_CLIENT_SECRET: AgBXzZ9tQNmrkCIVHg3lHhgpIKO0kcvOvdyaz0mMQhmwc1Qrugic7eDcC97rFs5C7Ou99E4g+6vgnA/oInQuttddDhYd300eNlNckXsqnPNh11+1x6VPPMnM4oZJMOiq9B1KPtq94ErkM3QwMLTtkjEe0l/KaIpqafPCxEKkHVNEkjOSN+5fzDRfMYOp4eZpg3vbuKf7e2Brp0Bacwpjv9l+aeFaeiE3KixNjv0BQi1tv9SDyBI5y86qyY54OTLhihGuiRJYMCpN7tQUczkwOfhK2WLR2q3JfOXe6cNN4LMBHnTP2HFLDaBmCyEd3UkVWNd/1BoFRJ74INTAVcYezpOSxIDS8AHsprRKz3i2g8AMIl11xSdzaHujeYH8XTIa22higChp06k+sGPJF1WJPnb/r4rMdBLdMoYojQ4HTeEk8OURfiDQe7bboBzfW1Qr3t03kLFZCADna2tn5mgzc88fbo8m4fohIYcGd5ZAl3yD40gINIDJmT7jihdFpubP8Ah73gSbin9Cjw1fGBkJ/CmlJOQ4t163K7iLEEHXUHGX32gy0h/cryH8COl2uQt5WkGhwOhH+Zfy5O89vhBgNZsf1HPf9g9oRcHJr8uAEsmUWmJOO5D+r06wI/MNm4Yykf72YM5woAUviAVlNt5TfACvAvIJQyjrBrRJc5z0t6f9QZxr4ScRD0J7Z1bPI99TqWfCpIl9KxoJjto4boBxTQ5dELaCZn1KPRf5ZHt0MOWN9A==
  template:
    metadata:
      name: auth-service-credentials
      namespace: recruitment
    type: Opaque
