---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: candidate-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    DB_PASSWORD: AgA4zvPmF5Qts6Vxn1r7Xy3OWJogb9U4J9qfOJW+P7ONAeioJzZ1Dl605Eu9AKYHpLgYWlWt06j15R6LeGvPKdL7Lz7oE+yquc89IalMIIDWF8u3IQxBp9HH+w38J6AWOhRUjokCR0QAZTH6q8o4itewHpIrRM8YyNQZfycGUyM3PO4hxLnD256jhXfWr7kJxfnrVqujJU0tlQUsCUQs8ryyDgtsWpT5+AeJi0Egd2eVVprADUEHPDXU+mm1cpbEDQ3rR/Z4d4Uofxdkh9+q4yPlzDUTKD/Sk/W9qxppsz7AVsvfLojTL3hWerv2Mr5uTFh9rELrrdKVz+N2e/oDxJ0B011QlUjokysiSXVUJwZMoOpOBS4SDVxUTwkq3V8IaOtJ+wuPo0LAGt6V5OUB+uMIubY7Vn+gB8r6c21Egw3ytH/+sgxK+VZVcFP6VFClPIPAr+pekAQ3o8oMSLGxgCJmqx2ppBCOh1l38j7loBu55bET0IvtFmkbAvcbojK0JQwrH8XvhJiaJhcm1EbmqQX84bZY33+LGcpKqXu6ar+PdKUIgc8DkDP/FbnLjdDCFbUGBAvgusIDiMs7Dxukn36vFULvl+75WCysv4H0MqziR+By0Z9jPS7L8DJlgfh+GwFDIKAKlw3MzqNO1+U08ldVKmQX4iXgGuHRlFYcRBf/u/5J3UujEpKeaz5pjISW22Rmd4Rj2+jxRg==
    DB_USERNAME: AgCYQuBnhWT5XVbpScTP9Gwn13yFatLeZFO00lCDA4LSN8x4kRsJzMo9U5AA2aNsuMMqwUUlryKN4C8dChC4AeTc/AoH17EMn/a4FG/w7SlcBdaVoLzHQIJR6mFhku8CKaegirxeNSgJkBTIaf5MVcxBPTPYSywiCVpWDGDK+ziFFJbw/4AbiHN6SO+Zw+wUzxxBy1Uz3MPiMAfIuYQJ82RFpKZCeXNsrGMqt/MfDyRb69MJGhKknsA1OsZwECezQ9MafDC0EiRaNAzokc/u8Pw8ksyQzs2Fo4IrS1Y3VnMcmbuwcD1hyuw5AZ2hzwSnlRbCiy2NtdRhrlxzfD4WMOya+mN29rAOecQQjGqlALmxYlft/7eLgh6P35wQrPX5qWcc8/s98qfGDxD6QDBPmkiwxAQzzWkSnW6DWC+5XduDvvUKbr4GIHbg36MeZao1IO9h7t9kYxm2oakAGg6kPBLXo3jk501gjtKFv3RbpkgYyO3Wf69FMaR3BN1ulGZLlIgdgzqXxQFZVdGiyzLktnu5Ob603jjCZTi+1XIPAeFRmUUOFRd+11io8BAZh33YUjWmSHOnK436/jy0CfPQEbjWCdFp8OPlft8cFHL7ae1KM9GDpR1zausbsWLxlLPdZtsMHt38ukplY8tve1JO/Gjw/xdgeQ/G8EgfwJJHnujKjx/J+IjV4flASurjxUmoJsGe9t5Glg==
  template:
    metadata:
      name: candidate-service-credentials
      namespace: recruitment
    type: Opaque
