---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: employee-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    EMPLOYEE_DB_PASSWORD: AgCKR/oVBemliq+PU68oRvP261rw72dVmGuRRbFZTU1qHakl2JycyfcnCcdyTx/E6aHevPe5wVpj6L+LZiBnqQ621oD9djNg/ou1niARfgwFtQrl8LTPxx8o7AEKFp0x3WWcMqrwQVi8WkKMJ6rjzPAqr+tZ5Dmda8X4+0QDOn5CVKy54IISgSd5m2j/VYZeacG2hicEDYPcG4aMAcTVYU/TyLS7HEJn0oM94GtT6oV8g6vki6LnHdp6KQ4Nj65upyUPXRaE/baH+JdbI0zpcMld1IL7/woyVYxHKSkdhmuld5a2AM+ctp7H/ijvEkqUGieUOM2k7xCkLpiBeAgkfY2hVa3QosR66lvqE48nxF3iKKU5XB3bCW7t3IV8+NqgGHd5JVhopaB2JjeHSlkSyYr3u2tJHAp14pSWDJuXO/eWi24I4WddYM3nvBAtajXDeMKlyh0wHGX/3U5/llQ3N4a9Xkw7HFUQEqMKfqX07179y+IAXeKPrZGMkRD5UmMU3SYPcl0KqX8HdlB+T1fMLDnJzdpzqTLlQqMwEtTW3VaXyDUO9zCJlXu8fxDn3DG4OthJ/RISDJJgOtCX3VtInzU7MbUngqLa49lBFgfa4tD/a9952IY4ccKEShAC1sSpWjzyRxmvmoSaMCarondzYSxo1yzxbnNZogOTQJKpwOclr8nqjCvZToRQItMavzSgzccmyUksdNmgyQ==
    EMPLOYEE_DB_USERNAME: AgBF/zKpK9PhRUfDeKN1zqm+RuAmSqTcKuNmNBmrzuA11LuGdiBdoqzQatEkHE1DREuyPApm5HwoAoqEfo9wyfmUvNwXE31O0hNx7MthAlNPPDXvIl5AXFjWlb9j4lhM1AVcuDM4x7Lp8MmTc3MEhnUoZJvPjDoN45Z5lTSOAZT/glwtlOmThkMm6mRBR1yVYKdhCtIZjR/oaEJX/n6JOjHgOiY4lA79PbIPtQchI5od+e2UuIuBKswWao7P3Q95LWaNibN5ikIpc7mxGfBpj6ZCUuPBcpKvgsUhdzpSWafrlmBypcagBvIx7pN0nrrR+80yGL33r/wh/V6w/yRye1a8gsun6ix7OP+xlx8Zhxu61cM0q+reWpkEoqRU5KiJEKOdWC24rBl+HXdIR+TL6FNnXLmT7T4zZ4JnJ+/WU98A0ovn1oExTUPsRZ+lb11Og0jn4TcPlj0cNiadilrjvceuqwsOBqYBpVes34oWqod8zPyK2BY44b6Tz3+nyQb/ui3Yu74lioIiI3bg7yr8KW/KhmDlUMwjchAbkLTzOjXRtC7Iz0e7QHGOK+qAed07i6z7VzxZFg5yzP8Yc5sUc0Szcz9BA4tuYqosrt4KvAqistLcKBWQjiJbzjqMt9TWkd+Sr5l+DW0WyJM1v4dGHDX6uQ0wsslu2ghHiIVIFD/aF8Abp6pqP0EbMz/OOJWULAEuJ5w22w==
  template:
    metadata:
      name: employee-service-credentials
      namespace: recruitment
    type: Opaque
