---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: interview-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    INTERVIEW_DB_PASSWORD: AgAx14i64ci9tA+Krk6ap7sBG45LbtRD+yhAjkYdSI2EhpAvd5z9q1D6ocE4Aj4y7+15WXGoE2OVKLqL6q0TvsljnbhRhtRky8cO2kQC2ABbbTUUOeWb/sgLm31IQ0uMkTuURLfLhbUWhJnBZA80db8/h2LxnQc4hUOKqdQ1LBWE+eX8GMsSGLJSxyG6+ukpO8m7uzy9Me26eTNw6Kb54eGznhUzvD7q0Sb6ULqNp45PCsXrQuWwJo9hdNf9XRvPygdE0jReGGg00sxnPKi0cOvMB5HQN38Z7WXHg32RGpXPxlXiFa7FdLg4B7k3UW5sjRWodLYHwtJHCmDy83n9/TTxrJIaTxQW9zKMsT/5jqDUyYK492agvQjTpDjKyFNMY3+dYuCCHDAY5Ozl21XJiAAmUVGWBgOYrFcw1aU/QYVUAxXGsYyI2wz2VVPE1sPUdLWFajlBZDYUobaTHoFJrBFpZ2Eu6mc2oj5agTJKfHX1g9yAObHVYe5Xt33V7DFWQZVbKq42ZJIhZ/fAEGK7GCBWtlY5FkVRlLStHRmL5p/qrr+trrT140LTQhBSlVG3FurLwC/L6zCaBMBIxN8bTD0iaM0x2UMfvF771anqveEwRzkfJRJdQxlUPjKyV4TiKfcGtAZuMHuErz8YhPA2yv8J+uNykAcBAYj05iwXSSLm+x69iwcImGA8r+Q8i9kCAuYLSEGLflsgEQ==
    INTERVIEW_DB_USERNAME: AgAoWnHR/9ou4Bwwk8N5pNjJJjwag5BGUU6J8ko+4+SD799ZGoq2S/rUiQ9WWGpig4pXEqxE5dsdBkuj9VypxQz6rdEqVIDpl55UP9dDlorWLIwmS3GtlL+0KADj8YCWKp8j1dSRPyRimUT6fYFcaS2s5fuHlcQ7g6CdjqEQbi5NUTcAErnEh4viYrpdIaahRtcGjZcwcKc9fh1QG/TmOebc2bOREy/APVB4Sp9g3/ym1C/fZ7hR+DkwKk4PXBlQEjZolFckIt5xKv7GOYeWWTDOIHLeajZL5VTIirQTJlQ9fA1n4hyGnn+slebBjDmY8zyei8n881BIdSm7yAWtSyEQsEN2OS6OPAgzz9ZC6N4MM2wLKmFiMpWEspgXuEkNa8/VaNhkDtwO113+5owhUQPQS/4GvZm187ayQAEtIxAUWIzTtOC4yCDjO/9tRpdeHQmV7u6vmwdBqfttYkIWSf9+D0toOkTcSh+ts6yhg5itSILLEYQd465n2gs6Cn/jeJMa0ipds3LEUQadGX/2tosu1p6S7P16YlNJnIF9qJ7qP+GXXU/pOdJJQBZ+/1YNDTrIqgv7Q7AItZJ8Gwne6XStRT+XLdf1uelE3POJF/TPpyMwvzeB1oSo1XPiLBdZvvp1vxPyTfWKBL+YZoy72y8q3vhthfR+PCzcbaOE8wTjUgaGq6XmMSWFMRDV18YOqfaBGoHang==
  template:
    metadata:
      name: interview-service-credentials
      namespace: recruitment
    type: Opaque
