---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: job-offer-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    JOB_OFFER_DB_PASSWORD: AgBialUZXbPOfz+fXyqCCavngkR9bio94zSJJb11pVY2GrfXlv1jwDMsQonPu6LKfjDe5IJTxpIS1+MZbJ1df1PMoWagBORqBduJIOoAQVvaRvizHVIsXkrDZAE6c0H4ybnx/LlAd2SV+69wmTV9e5GwOZl6OsmPo86x/hLj/Ce92bWG1QJ2OIz7RxLzSgi/ZTFkstduzAiNoGG90aZH/j7FN9qN2eL41wAMWkUif7vKroiummymziCC6EJMmA2lhb0dKBPcnCNDgmXJQQAqy1KkqMToYYRw0fPvEf6aos4LPb6Hu922A5PHBryYYf935srKX9/y6gJhQe5JaXlCX+sh51QfbE1HZccfBou7hJIIgGJAiA1wDgnBMyK6Y50PM20p6dv/Ziq8N5NNry5OrWqUFneXTPc+745AwevrBtXawkfbdVlazJUMw2xmh1Rt+3qNsqTa5EH8tp7WngVpgoIJKVSckvGmLCCJqgiZ4z+22D3ZksDdG7L9+Q4chHaEbBoxBZW6vhnCIijXWqHh8l4blAJKns+i/ks4dJ/k+bvsz64TYlQ3TmhQ7BIMBMutdbADFSahV8t8vosfZOeZsXeYOZ2Z+pu7KL9aBZd+AaiPSzIZuQ8IskcDfclSrhX3HjDKIAhZucTaVxBBz2L5nNxmPqJnB5UBuuuWadkbbmZmIMY+yy+5WHPj+n5pORqr18ZarysGcLyKKQ==
    JOB_OFFER_DB_USERNAME: AgAownERvwN8RMGQRG/P9OcEwBoKXGkeRgTEKstEZxoPAYpiFrWsq15WSpSf5DvT+vgpm6006b12lytzEslIKjtCDcrLfjPlhHHT9UYLVFv9FlzAn4yoqDOVPqcIBd144NKvN274GsqGdwDhEXrcmikg6H0akUi2cKBRLMto5AfZ43/dSLZdoRFXRfFUZvJONzJZpjwasFg6lBgpcQeeCAgVXib++WPqRlzhmGNsOF/AYlY3xxkKhEzjeToLJ3mOIWSjPIXzaC1wqc0UtXlcEanzq81wQR0FX1A3lfeYlpnvkIzUOK7A9iWVhFKa1O3iTY+B7XwH8lNu359fG50KceHzCDovhhBRy7iywly8bfI5ljgWQCGBvuijiWQQvEMtPwfhIO46Qj1RbAp9mMafaACKIJk8b/hjomwYC2/Iza8GxrIAkyh1igsseHoVxduFRC8pyGyX9LfRt1oEnSFG/Whc73Uw3fkofYTjbnkp/ncvrgbqErviCGyf7oDII0IWnxHdp+mXt3QAMEInWzeRM5iZgQOA4Dw+M2r8oIIAVTjtDqkBEbXLgFTTGqZyXTDDDUs4nvR+/zPO5xWwuiHUZLCwr+7eHdXVb3ee4yUaJswz2pH0Nv+H2gSCHP6Kcx2ERbarxJ0EHOiViCZGUAfEOCUkQM/PPZSk42m7ZwDG52bgqazfdiUDYu2AR7nsL47GRSnF9GZEhQ==
  template:
    metadata:
      name: job-offer-service-credentials
      namespace: recruitment
    type: Opaque
