---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: recruitment
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBkgh84UmwiK8wu6sXUNWSjmc3kHPFKYIIGPUcPHKl2LWImPi6va2YNBcj/5Rxljy3IfUHtm584MyHRR7Rn2bdOw3okfPpRuxjLGiKRawq21Y+rMihzu3eIOZbplhx7TVmI2JWzPy8lAdS6ytV7I6jE8ab0usiG8Ry2qex8YfU18/DmOfL/bN3/CrkuFJdQ1rTWO4O1GCxkiIbyW2CM3EvfFo/qMmpqifZKPFl5870UJrlxSbozMP8F9wcu/bWeL0Yjct16QuP4YcaMan8RbcnT+AFVWYxr0rMYDHw0mB65nxfSieO5lCVy0s62yjAOFFMKW6+8hl2xGwVLQ6GuxAwuB6OklSkeUHI+k+JpL49mx+m25Oma2F1GkCE7p23EuSGXi6hslPjMwLHnxJMV3MOL4LHQyplW32+8VWqt3ig52qYZsk2fQ1GdLx+BpKRxrzgiihLsXfIL1s86/Y6acuIQ0o9rclph+ITWhatUMFOlf2EwAmP2JvIObQCFmP7q4zpJkQoVd13HDygo7+XWFlT+JFf46zsVrwGzu34R/3otXRK868z2Cu1cs4x3LS+YPUc44PLyqGkb+j2rVQhui+JQGMlNAHfHSCXM+SFxzro9IH7EXJswUw05umLpdfKMJmtjsJFoFmvnl3HzbGLEaMpdoXGEo70qMll253D1R55qrk1TiK32QQTNFNfVFOrIxOMKu6Kq3ZiUJIaB
    MINIO_ROOT_USER: AgBI3ufWGatsp+nihelz658vnLykX046rt/ZI4iy1Kjy+TqVPCUZUSlmOjR2BOujcQYqUzrQrJGxkUO6A/R/Zj8JndFvjiG73qAiD1WWkfFwJIs2YLGgnizdZeiPHb1p80nkidjxPMePFKdK/i70ID1Zee0UMKCR7ITcDQ2UGTgZzuo/rPe898LZAGV7gp5V2F4KO1Ipgh87ZCwOrKKMqdMv8Gj92Ki6zMCGgr8wTkLbLg96czu74gHi97BlJXRSKpmE+rHx7cKWh0xYK9e21gweUxWRtKYWjT/1hOQt44FPu1jGBnZVEoGfUYwAWJJqQ7h3uyplITdwQ3A0Q6j1HDGPliS8CYQ+8pI9bUzDKXYsXMMGptxjpt7DWQNuAC4sca8weZImHf266MtFEdZmz3RItBD2TqGvaLyx28BatBt1LhK4FE3GHpXrc90cQnbFj0o4vq9T8+ol0K8a7LHrtvPfjY3v86qWdi1sWQyI3b4a/UI0Nkn3WT7xqtCHA5FbwPLZo53uwXdisB4IciTwwrgLEQTgg4iOHBF7loxVZccTxK0x1JW09WXQQMIVxClni81Kqje7cxLKk2Bd9tWPvZ4Y4m3xDY8DphUxLfmi6mmeZwMEvnekBi9e1acxSa0m5FGU6wf6wr91sP0QfGmYLmFjKwpmQRM8bMKYuqoXiAAMZ06TaSNDlEQk+6a1pJ8BCqtoZbD4I9Tn1sF3
  template:
    metadata:
      name: minio-credentials
      namespace: recruitment
    type: Opaque
