---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    DB_PASSWORD: AgAma9Sy1XjlsUnCaYQqCqolrK6aE/nDHPM/RzDdu9Aq0DCHbSNuahz4XbMdSdOt56DWpZ65wG9/dhY0BXFQrDB95mlrkqvCvKuk1Gsae/zIVgP7vw7icgn+w3l7YX7rpRXgQ+4V4+8r1NKuOq3zeR3lWnsFsjEzLi9VMS8Slxn6rQZhN5VWcBu/i2HYZgIFCVL+c7ZbQYAOfQWHaRDw0DDB8CoaKgk5SxiXTjo8yK0ck1nf1pAKVTEUdeSqLrIsAirrPL6ltmI2M/0UwdHtp8l2pKv0Wnkc7F3HjnA/5oJdAhNmIF45q/1Rhh9Y/oDoV0+fVetcX4+HpUgXwd+gq7Pl//Vb555sjHmGnBfhrP3qPoeBTp5QjMPkgOIveZOG8xLCRXcn0MdnCAGnqXpypzXz0864cC5bckldBe92tiQ5y62mHmolX0XJ2+8xUahULfUsxUsDYJ6+8y/sDMs1WROnajoAmqZ72ONW651xfGANSmS00VpltgEb0pbzvVttKtPellbuxsTqXXLu1QuXPR2T/l4sdlIqgZzAJpyjmGU4f8Ix6SdRigxIjvw9gXo6rIJOiQGWVhkan4fXlt5rc0o7JGGtvbFsGm9ZsVElIkJ9asPzUF4ydxPHZT+CLgFQkKRDN8gjXPFnLnAXUbbr3sQZuceXTOo3CQFV8bLNB0Vz0jmaKZgtzczFGFrXeZcCfiArOLKelQrAAg==
    DB_USERNAME: AgCK03poWQR/hL5gR1hUXPz2lyRuFYYBVa82EOwxOEhPWBZxUUu6nQNg8/YPWfvHU205jZgIGEGhipmr/mXOoLVCdDaBWW2az6dwwUeX2z1d6YrMZhtsi20d0deu5Q6dySYLQSE03Z6C5LeFx57kRwgSqQ9TUYIfMhoGdVJzCWYhcJCBf8YE6CQWGVNY/x01p9OpIucivZ6XbmlwGfmKTvWT58vS6gJrHtiwqO80U5VutA9NY4OEoy9v0jBH3HEow8iILJsamcGpAOTUAqQBzt5oeKgCiqdoJaM2lPmPcmCjziOai8kjKDSoeL6JMx9MzsEswvyX1b/Df6vitah35VWN8A5STWoBu1cgKhYAi3YVfGyA9r9YgNerBVGVgkeMLt1fAubD26WrXcZL0i+2Nft0sXASYE1Ec6x/PPuu6yc5Gy0+Uy5bVquAJ+ltGZ1OVvpsaG0UYfBrIUHmunWnAcYiDZWKn/UbPlh0IgGi/Xe0fRLjaeZ29566iAM/gKXQP28OcUqC+XhP9My+iHX6Oe0vtbakobutRWzKzovu9e1uGxSqAPHm7OEN0tjwfwtF6STv6CnxTL+yZeR5UhYsUzDdv4jbwJgYPbVJMzvhIUYSOXX7hgLM6zceAcLtF74EcXrgAjkujefzOhmy+x66Kn18nxb3dFLGTlH4SLoiVsLSC3nkBBZsWoBcbrd1rzTomQUR+AeSLA==
  template:
    metadata:
      name: notification-service-credentials
      namespace: recruitment
    type: Opaque
