---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workflow-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    FLOWABLE_DB_PASSWORD: AgBBfLd+i8s36dx32z2m0vMnzfzPQyIc56+8FhPAtCh6DH7PvUG2ITIfmlAsMMWvfJBoSfo04DbZ6ciP4m2GZNOzqFSl0PgNHuHzzSieV51xLo2NcKmG/iEjikCRfrK7lBJpKlL+w1j2vjRgPGBaiFmtyJiUo9LIaBQ8rl6Qq3DbamMUnKmGTmapsfK99L/CG9HzxBymTuhZSmWjsovSpmlU6StpTTN6LN1bH+fOViLbIiqE/erjW5V29S94IapZw68KBOPUUAwPB9sxDHSOP63eEvD5EFahEtq5OEaO0udsB3j2DrSAKXElzWh2yWcnfX5qUQ+xfpxWjOA9eE7oI8RxHTErsLBVsg782eN8Dfoc9AQqPrvVC3OOv1uUvDWmKS+W6OnMDhcCDb4suB84rfVg0/KlaQwa7dNnb5ucoUpmWS1X8D1jY/c2lqS5vqI6DTfBDf3y+B/KpG+rz4ugchRhKHi1K7BEtixL/8lfB4o/RSt7HklSsklWgWWDWaOQJliB/HBUxhvZoP7jfUM1bjd861IGyK0+JBUZIOJ7qoacoMDeTdItY/7pdKldemNqmUcuDbCgg3Eksj2zRf4PvgbTAHbAGw+p29rbOYHvvnOTB8b684gwtufJhFC5Cy7h+lYrsRZ3g1PRkvyc833hdfce2ZXWzjXmXqlSZSTBqv7xkkwuQDZrPpQNlrfYHVD3LWiAiDd62F0JVQ==
    FLOWABLE_DB_USERNAME: AgB1WjTmIDjbgYRbWWyc52mFt6D1wGXVSMJ1kd7Ezd3H651wrn65TwjunQ76J27JbbHGGjqBI+T985fwBsjPy+Vnoa+CHPXv0dr4PKF0hyKiZCvHTEYL07+WHu2ZWes3Y+/lTQwCcn2g8Bk1HoAkEz7Z6skHgEQCYkK+YP9ZS4nfq53GgmYm8jnU1U1FkXW8EIgS9yG0iVE08CpZ5n44o5NWWKmeF+1o788RrFsRddpQBT+lUfgKJQ4AcSEv1t7EVJogNz84NBpoqFhRHdGtiqWkoogHwh3N4Qz6a4xW7KS9PgYmnwRWyu/j3uU/NDnaXvFfJ8PMs7aqYZ4d8Rs/qqC6hXVeoaeke4CH5f7mqmauWbdGBllOULZiGGX3oiswPA1btpwup9+/IwDIsU8Cxed5Mx04rv/zIbPoGr9fzBL/HeRTY2c6eTBXkzxAiBrOvKgFzJ03LcH2VQ8zyR9X2/kTbY6+2dD935gokIW4yL71Jgr7tuEvlAOt+E6DB1tqlj8dpuVaGUvkvM4DAMNTce/TrX9qQSxCWmbE7ldmpiwLRBfIVOUoiT1VDngB85FSAEJbZe1se7FfmhspI4elz2Up0qPDoxbqepkvtoZ5f6veZ1VUa+DAPpX1uPRISWaPckDo8mHdo2SI+7X9KH3AQwRPVFp8Vf0qTjWpu6vXS3xhRoAC0PKrGAz25wOxxaFifA3FvEnGur7QXQ==
  template:
    metadata:
      name: workflow-service-credentials
      namespace: recruitment
    type: Opaque
