---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgBXymR87vmxx8w/wcuTGdesC2u1RZvUkoi0LTq9CIAeHHedgvGIuNLl3T+NfDYs+5RkHa7l0HOrQuyTaP4PKBR0T1eK3WjXpe4hwIvdVRjX/lmicXX/Ri2RoDR+v+iWWg9UOT/80cxKQnLC4n4/ahk5A8cBWDxEGwN2rcscA6efI8AZjJ5GNT/vsUQXCZqA+KEawwgIDzNW4+l/Y1J/IPPrrZ8+4L3FDcCYiUrBuf+TcL6tCIm0HhgcqbczRDmiCLPwck/g8AKZBRMpqBSPd9kwjwa+nY01h4GjPxFcYtwNGvp6gwmxKIBcH4XJmXKzLhdQM9qIsituvKFGtALlQVpY0j+zJBuY1TBrZeY6H6ElOlUAsRH0nv8JR2jSqGkIxSnrKczJYfVF8VFI41QsqeKcT0hx3J5PEDyXXXfuH38WVHDXvqlWSYb7nhdUG3HcTa/LnyFe/DApHG0jY7g4GiWTYKgv+3TAO37Qp7eCXuGIwd/lJ/RnvJzPFvu0F/XVI0biC++zy084ijJ5H0ZczHyZD++z0wK9dv1iKt8a2bw2p396MIIRAuiSRi97W5oXeFrfrDMHUInqv1UI/gq1eLUUEznv4ng85ORit9btaP8mTbXZ9xffUc4vZwal0TBasNJbNUfYgLI1uWiw4nBgz/l3qHRKjuL9SD0m22fwJv5NsUBzA/mCfbq+52AFqZiK4+U4/H4SO2Rm
    KEYCLOAK_CLIENT_SECRET: AgBC73F/DcyXkQPUJcoE94x/2RLaWW9zw6yGZ3iHVGlgTSFySja8/nHDEUbqWnH2aKk+9qpb5Y2uN1mgqXV5I2Ko84l9dmZbtnlN9EaNFLfhxrVoGsYkK9PV1/zBf3TIQLRqFCBDevM1z9nR9ZjRhObhQfrVUR5FMVFWkK1XI0puZsNZqRbVAuHJcU2vpQ8GbILna4T3b36lKfITmQF/0EI5JIxlHvFANBmzsKE3tEVJqr7dGop7IFMxkd6YAdakrt2cEXtkOgTdTzv/RvuUa/fEk9vP3Ck/n0JuR8UQwQFPZyEtqrfMH5ONu4qfcF1j8VFsLKW/b65OvP/EeSPV57uiziqjpfS46JlI4bo+G9qNmF3VAmbAqubqDOfLkG1EO0AHnD/9PMboteUpvqdeB/MBjx6bRJC/Ggl96ZDm3b3Cqiu8nLlPJJm+qDjGE+5xYXMCwrpspKxuJxTk8xlKTbtbhQTutzSvvEbu8eF0wRqcklXjwmKpAZp4UpB3pNoe/Zr8HjT9oTiugiJcVU8xe+eBopQdGtnTcb9Thd3LqO4O2bd7+TRVHiuq2r96Pgp9BrsOK2BCysi4+S9sj3n1/WDzzZMSK6hs68qN4XqbLytDkDgHHWn8PvhTNUCv0eP4T5MyGjl0zF5ZkIA+0rdMzLlWUsolCnn54RWQGCLKEOD27qBvat6c8364FKIfOafsB+4WSwyOhq1NlcBTJK30T4kM/uJrXR1c+0MX3qC4STDJ/w==
  template:
    metadata:
      name: auth-service-credentials
      namespace: recruitment
    type: Opaque
