---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgCmCs+UtQXtCv3Ki1uPW9iQL9lnZKZgNBNxfAG3XszrU7k9amr1qUe0WO0Twl9w6CGY790TaOnZLB2w8vfkhQBtDNjWcAqixETX+lXfnL30SkKB/IcBl4+ZoZQajry1DITlwcC55FuiefbK41bGM4Xb3ClZ4SNeqXGNMt7u+Gc8NC6nroUcnAspAxb1kFi6fZ0Cz66jPo7adms1oAQhQVkyM4Pf+TsO9sKwPNRtDNV4ZGW56BZYqdjXrHtCSRyi5L6cSQPCCjA0YEFWhnDIcGrRPTUcoyUOdxdugVN8rhE+FTpUnyIrzqbLXufFDJ48ne0ACbAs7mO+acRkfuZ8kemLeEb9C1uKQ/4PxfwScA5FX4t0mjJ1X2arB8unHazL4r0s50er0PWgXJCPbwNW6X5bRtjWbXHCG5WI5TMBeLbVbzcnrCkeIb6tWGuzO0efj324a31wO02WW3o2u7wM02IPjHxAI71XiKg/EKYXGCGrBjietvMbiDID8qvNNEfukyPhYgaQCNJA4l7dzw1Baw/OAzot9eBLGNY5r8gm9CP0Npn+JWMcIUpDYLFtm2oz80Oj3CzOBm3ZZkUpWaNVDfQm3xGbWKDF/aL9HeVTiVOYNKf2E0ztuVMzhm2gU5tEu+0FfOkR+NdWVLtDWr7BuA9HSv+NkEhJrZjwHQs0wEfysTt/OQZL/AnsYA+asbLpAzfK5dtwZA==
    KEYCLOAK_CLIENT_SECRET: AgAeGX/gsP3kTKJnK77bA+X7N/Dz7MtAkEXGIywVxc6qyMJMaWBcyykiJO+Bs8yWZWEUynZRT9RrIJkbZ0TCOaNY/YKMs1XcyuN8uEfzodGmbWOPE2Q1ob6G4vAPdnHgjklAgOktxLHTkQ3dJTIGIopMk7JybxAcLekOrO+/4uNs4P3eK3JpztqEPTkxLJJ62D4Gu9u/62dLGS0kbU7H23JEZHsgPenHCVDyXbAjP8aIeAhkRjzVyLGjEiDohu3XRW2EdNWjKxmjHS6YtAz4UNBCVKRVBuxFz8gaolveKXUwlkkGip1ydOroPrgVMo0QFsat16kXBoInEqq9htJovbMC5dL2cOE3Ar6X7Azzc5IESHRbQvo+1rDbJWD2JP+pRp7kqs3B0pHCt0Bq+c/e+S2uP6X8dOzoSuw/deGHdBh2+zUf7AKpmMsrFqIpYEpKlOdFs4EBg/23BoyzFMBIOwyhLvrnk1AR4G08XOWSJ3XAObobKBlig66ncJ1vNRadCbCwzrNp4y++Qte+4AtO9WD4jkS0ra8h4O4yuoXGV180wSFMJr0CwKUO/q8vVJ7nyeKEHLh8nP9Z0y+ZzWSypvC5uZxkJWwpoMm7Ms4VYm7zy/4h9oPqCWxkHWnd/6gC6/VaxRWsRTO0qsDWSWqTuoIf3xig6gvrfxH5rLJwnLoSnKQG+posTjIlmaVtaxMBbz8/Zv0IE0zy87Lna7MULnz/aMI29bsrVbetKguR8/nZSA==
  template:
    metadata:
      name: auth-service-credentials
      namespace: recruitment
