---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: candidate-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    DB_PASSWORD: AgAv5WGQ0+dw4P61Y9fL9scC+r9Jpql9JIv+z6IEqUGkiACAjpi40T0Jr8H9dydIjAtdD0Y6y1G64R7GPjlMqYg0YFZcNwWi3RSHH5E9gAIqjhNYhtV1E2Aeu4DR+2Q2axa29Xq+wlQHY2uoi0sj2z4+zX4M0CCT5uP9Q4PmBQdrtlGjPBHGr16d4NPKJt8E9ch3pdBD1bJdPKreNV6/1mWEOjBsM18QJzjjjad3/aexJpeTIW1u0DFwqXwRsOWDZf48Gk1ua+w7yU4cWlKHxetCNT/icw+f/UjUknzxOIqlAnJ+FUXOHGPEO2/aZkE5QljeRlVceXrBDTnez7WVVZeq0ZL2WsZeVIF58BNAmpwRXiUy6G8GKOJOSO62YfEilqO972ENGtlsjJYgFtIAoNiauQL7uoPQTjLtRfg3VzsVx2H2Ap+2b0bDdzhuE0Dsxeg0dkxnfemF7XW0x6OsOEt+eh6RxwG+V6UgPVDFY3goH9J3xPEyrg1ihLqKbt5MZCHuDgW7v9OtMOuv4b+OV/qbRAeYt7jUs96twujIlf0IVGY0sXhuMtalUB/7ZYTL+qFVdpvraRD2P4MvtqNIhp0yzkVcO3ZAjYrIVzClUxl0OTsi4og107/u2iIstLMBFd+33DDmgNHaPksq3Lyxqfz76DSBzr4NHhu+cCWt4MdrNWoO149oPhYaYxnI28KxQPm3ZtcGoKmelA==
    DB_USERNAME: AgBPbex1G06HJ3uTz+UC5LvF5STWXQ5MHnJnZEd/EYVt6HxPG6uoN/womi3LVcTrmnyAsAcoJBgNP2r3VO9kx4Y4ODqg3alzJqNd4juYhjtW9MwIJwKJUwhKD4UcLNgtRIPQNu5/Ls8bqg9yOd6f5WRiJb9/tFoeiWt5zpy45zP0ysz2KV12IWvGE/Z/DPBwlISmdPo97zhelLD2AXoWyYd0KB01GrUlqIK40ssoh0vW0nGo/uVVBYEgzwx/hkcvWF4pDhE5o9+iix/cmbkjSbDa3lSKdIR1yqYjScnVMWMl28aY0BJgEuZLXtPVQZRRiARVpxePgMBSiJlVeGOC+iqIhodyMkz5k+VMhZLdO7u0F4HA/sdK4+As2O7rK4lAtiVIdjXY945lIIgdMVwRYej/T2RrFq5gWxOqJ6kjeD+RLtA0XiieMd746eihMWwu/kUEFW9TfK9NxAqoOc73rL/mdtgxY5zhyNJ86AqyntMxbX3u4pzAdeDCx9WrO0FLptUUp6BkVzyJt0HDc2RAD0kOGznBxK7H0TUbzjrKy+fxyzeVmAoxUadrmdNparhJ5iN2vRyhkznoou53DfU7bc6dI5yFWoxfv6wJ3xmCQLfDF+2nzPGv0wiYbol4WViqnjzRHmWcgoQ2w7mIIkY3j4S6Rsjy0g0k2XpOvOpPR/c3LnxME9psm19qiYipebqbr/wpvUOthQ==
  template:
    metadata:
      name: candidate-service-credentials
      namespace: recruitment
