---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: employee-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    EMPLOYEE_DB_PASSWORD: AgBRw2d8KfHRpsBDpp7cEMfBRHDTUebG6JWZ18MxGfUz+yQvHJhW9/UqlCHKZh4xTRrljac9ajE0Ybw4s+73aVPePhj+fm5X5FJplcJGKpueHcLcEP/M+QsajNms1Dr1fNrI2jw5FnaOeTcVdlYduiv2uf/8+oR2BWq+qhSQk1KiQnUd5rtA4zvZdKR2K2IF3UjOcgLFKypUXBlj2MHwnmmf5HSrRZysd4XqZ0WEgqZIsuvtq/ZFi7SfO7zzJoWVOde94y0Qf/eTWvYMobFnHpV9ektl2J5Gfypx1p76Z6ClbA+CmW+60Oi6iSzbx9zzcRHoE6CFB5j27mik9rWQW7Qq/duW+5OG6CnqqchLjdmJ7G/lgUhX2xojDNKA0YyNUgRVHP2yCWfTJxHdk3k+JFIu6YiOy+YOS5/JnzXJZZVJoBKbiRFc0r+lEFyGyHfR0AHOiVKQy+y9tiU6a1VbFHoEORRd5QP26uc3M436IrQLf0qtwZFEa4ahPbvOIId63Ptm3dnw5ps7S8s2HrUXFg3+8e16RSSRPw1ceQham8iQtbB07ygcmr+Hn360c7GumfBEsIPkj73GIsaFzF5XndioZP8FgFu+t3xSqGMNpA1fBYmMEgR1bzBNQehHrjZiDFVL0Zhh9ibz3bMkPfNDWuRiYHgAK3hG0Ft5kg1GSlbTDKPYEL/OELoJ9ni5CgsoC5D7oHb1JNChBg==
    EMPLOYEE_DB_USERNAME: AgAVHc1472tABXk33UI9suv4dyT4eT+Y6jJ8ZnWiBjOdw9fZ3L8BMYvikq8prTOnaU8jXi55xxeqwXemAZ8RTVa71j6sf4HWmRD97ab9ldfe5VtOXwh5I/xYLHQ58A5fSpNQ2LtH/P58o/nWMmRMMnXQzSzUQzkY2f4qD7WMpewqorqdgGGB19DSb73P0gxuonzWb+q0TMoXP5pO96/+2KIWZr8WEAsGTKil8eahV6GTpgksv6Jd96ob/z/d3ChtCp6DGB60iMDznwqX89ymk5DzvxO7VpT83f32Yakg8JEmqyQEZH2W1/7uzSs9oLgD/qNO5VHLoLCRR5yhHpmbYQYS3jCAHpPihIVr7caAmh+Mv8jtyiwqdPgc0onefgagGMBUcBWCeVD+yEINEHUkcor5bCfTePDSoEV1wpBkc3U783lrnKzJE9lZ2ohA+JOL255M0cmqkMJvY3BSQ1/mVLLq4AE1DtD4BrUS2egRIh+lT46V/NcTREHhlGzZDH2cERFDREXZu0YIFnk5bxRMK+L+hlWK9/cMK+h+XAvKVew2e1MwmxWwlrgjiywJtqSdIkfL8Pam42X6b+BZr22HM4NBSEwoi+bhRQYd5iTSib7/Y4XzZeLslStmCJNi2gawQkEZRDgkmF1N6TaW7WY27xcNrvQTuRGDmGxOpIGBRog7UWgazIBiY9NWj42vQQhovrraz9N0vw==
  template:
    metadata:
      name: employee-service-credentials
      namespace: recruitment
