---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: interview-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    INTERVIEW_DB_PASSWORD: AgAeNpjSM4yFwj8/QxCeI/3i4uNC5bJUE4VnuDxq8YJDC9wnGUlONdW/IHvXwOLJuPOfUpsO2aIYKJm8OtybHcZJXvW+JaU8XN9BKqFiJz+TxPGmryMj6uy7hOvwgsER/b1U0+oQxEwFhFvYXO9Q9jsBv+tDfUIXlUTFUH4J4fEzb9v4f/RwZj0MmNlDDMScavS3o7LnHIsBxqx0S9pfEEYUEX05/C8m04zDPM/eUQFysr0XX7fbpGOYSCXUx5xRzcyLavl2m5imaRgJafGNQxF4MPdMFh8y3l0iatCZoQSFig07mr8l5NiHMN7BvLjUUp+nYZOFhQp6jq50aCsSnyeCAATLH6KV6CXLz4vnrz3UdA5xpo1fMl6nih5jGCcUaZlwZLQ2bhG1y8A0aw10jbm+5uKdZmXp0O7mIh1e3mZq1P1j+imOq8TWzYmWQabFvLEUu+JrAR0bLY3aVne2kdQJ+25X2gMVTtX72jZI9kZudJMYjcq2l8bV6Djf2IAO7yDoKNj+LpKulnduSOxgq+OWHVZZPYJBE8PMmnqJaj0QWaokcpixCzZwg2XwFLtzIpxxBUPMycvN/QNP6bUwXO8S15Kk1ddb08ViO5TUfs8Y5yC3NpzPDw/MuXOkdZzK64G/5pUNudMtNoPsiVEjZocaFFXd9OudwiOuzSJCe1YNm+X3ufuRcKBG5rUBWwrL6jsiYq5X/bLZLA==
    INTERVIEW_DB_USERNAME: AgCGvyUslLoHXlemH44iFYsZG5bYEwX4Dw5FjsF64E6OCBs+oPB+Hdlz6iZbNDAca+IL9InNLzJCAVCajnvFTYgkhf2ACyyuQV36CM8xcb6vnW27HtYBeFJ68qQVy57MztfaR6IfUwW87DeWpXEUgCHrpFPRfosgN5ftp9NWdgddNAEZZR5tKh/eMq6MDxauCVqDGa31GuJ+rOCU49FaK7wQf9eUMmSbxKkUyFLB3u1wadyNF1qpqZzTUqyfRutmt4iiWm0TvAkR1c4CC1zN3nioNYWWup9CJxIfFX6d3NUp9ucIKmEn0QRqBiVor74vvuspiXrgCUCWsEe7rNubcKD8B0Ez6VxHjJjWjOvfwJ1wmdg1oW6e1E4MtLu/bBr02C4g5WJMtU3Y4vRxDQEU9Bqy/hfNyXm/AjkEpMuUJ6wu2lF/3Y+o/72qdJVFFxhppfPXORuZJf4mXMOm9bKWi0ZKlwBbb7U5ymkg+IWiOVSez7+35UxfkDoddraUwaWPolWmB8pFRWgQeVgtHUyjhaC8JsXZ+0O18bko4rS1sFB/cxE0kEueks5r4k4TuGz0VyBEpXc3tK+nn88dxrHmsqvR1lf5d2QyjJLR9s6xMQ3Ht5fNm1jIj9YAs8VeLCx5VveP7L/5Ng0qr9HCStjPBu9+HinWKF02ratfVFodu8237EO5HBw0PCrIk4p3xcGVFbn8y2/KgA==
  template:
    metadata:
      name: interview-service-credentials
      namespace: recruitment
