---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: recruitment
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA52LVMUJKFEm1GwAaDMP22cvLZsJv7HSEfNgj9eJZTm8eqVSwRK6s8Z/WxcORHLXgXPqJhf2AQ0sxsV6QNUTLxCkIs3+3ZHTOeIoLlPwEDdUy0E1IsEuch+oz91jZ75UHyJhN5R3yzwne6+8wdKGLyalEKsICpUIjPkDM6t3ojAaOHkr636qRAN9Ubfmkvk8GpV9GDyS98BfxpISpg9ycYoPgUt4EkqQmFRNIBPsrgyaXVkNBFGnwOL7BJniEHf9uTGWdOei/7bsbpXkGUHT3ir/IEE3a3HrpOgioRKeY7Jecef7nWLBs1zk2HrYcDh47GaRiTP3BWOrcJBCMdy/ajmoWJo8HvfCkFDCYT5hwZGCdB2Xn2K2CFa3BINNhtwysWQHHD1otcVbA+pcM8imaO6/c6gdTi/cQvUpuZnpkvoBi2k/p5t8ljeIf/e8FrIJdww9IcPSYI9dDM9k1qjr6o/XvXB9dFeyULIT6A5XpToqXTdfVP2NwvDh6ZLxLG/jwsoNuSea3YM/ko1gBDBazT7m0RQuVk3/M6jesl2IQWc7MhFQoRD+jrkkYpRPilQABD7I4e0MxTFrwu8Bi/92Lnv4KL52i2boV0XEAtdEZYoSw+mcdZZCipzW511hPJpTWMQCz8jzKqShZRQTsMi2EdkL45PQ0TI/tAar3gyI+4spbtOYhUT6Vo3u5fiQgZhQaZDBst10dP+QrK
    MINIO_ROOT_USER: AgAj+ln0NjqNssoxBtw6ztfs8DPypVvL3+nzQdOyOH+ijd0Hubr7eKD2HfvMkXryh8EySHbUhCmAWiQMi/0A8TPuRNVImze2j9ZrhLLL6badH7IJID3YT/9KkpgyaYqlpxDAh7Zks+JCkMEmWY96ZTHVLWq5AfsfBExbge1p8mmniapszzfhBQVlackwT7znn9+VWSyffUjmC9rp6x9qkRAweATitEQ1WPjE46S4BM5gnwCwETgUCFxP+T9P9d9VnT05MJxtfHZcx0baEQ39CLyo7vcQsqJcY9ZYMwIVB55Ta4KjhpO3OvR+f8oLSC0f9RtKKrTfRVKYgoECYawFFIUg4fhIFxSN7jT6QqSJosGau6S3qc+3FnJe/TzE/DUjUY/4iNEYLCQ9bgJHeoxDrAOSxELAB5IU6t0iYnWAK1j/jMu9pd7tYU+whyIBnNOfBrMu9AJG5gYEon/9NQVS5NBMjsrlQWvRTkZ2kJEg4jCdTWkTsRkekYkDLbHOtJqq+XM+em9aV6olGB5qcAeazQYsEVYFHSNKILXCFqX1BWz7k44Myim36wa8DFpYqQGIabQtU02E+aB1ric8GkMOj8BcmtbAa81ZighDCCrPooIbYwBh3kxyIwoSSF6syqMe6UWOxDvqw+ENkcerPvlWQyHDbyJkJmICZH64dpEP3lxdkFruBb6WCfYGG/4D6OJPiNv/CeF24Yw45jTT
  template:
    metadata:
      name: minio-credentials
      namespace: recruitment
