---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: recruitment
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAtmiBqdNfHItq9DvuBmOBsW2jDAvy4rkGmWMVIFw9ahD76RHW7c5uSM87cOh6lxrlQidLIoSKgQ6SFyJ8KQdZs1/dYKIG8Hzp0HAygZBQCtbysllBKLjEohKN4oJCyjnSZVEutuK8nQf6VomsDSLYXYABrUXX0GU6VIPcBT+7NcaDHnOao0js7EjsjKCR09F2rB8zj8gglPjFMAwtcgatdkapUc58pwgZVkISpxkgQqsNkKwcrrSw56xayJfbL/rR89ZVeDF9haLN7KhgQ9QLmLymTaPkThH19WVq1rvOaze0O9JJn029VisluyWwuJdpCUQPqrOL3uo1ss1pT6LNejjEO6D1lPkRF+IO67sh1XW5rHSEC6rjiHSMEVxbCkdTnNxyIx/Rb9VC9XqQC5tLab9ZqW8VoraoLlOSXpmZE5+mW9Veddmv0DFMyiiwov8+uZHomh7KHszVYwY0LFeWd3y8acaOS9LtJAhgRcw9qHkU3E2IDyEADhhRA3u/mUs5OZ99IPsb+Wu5ObLyFe9hdSgQ4MtmYIeAkqV47f25r3vGG8FSITvf+/T1cWNvXfkAAylSftv8ncLvcFW62txJksFpK5nsxBjPPgWx4WE2mj/dX/fS/9nIqQjBxYZsuRSoVQsTzAucjA4wWdDzcUbpx9LAi4qeDzCOTnfER1rR+yXuqN5AXbiSNdojfseOWss3Vg2OKVQ02gHy6
    MINIO_ROOT_USER: AgCUvzfXjxQfQZx321HJZ9DTCLSIH0w2x2RG3aFC57hTdJ7RPP7R4NoSUdrSrItEc7TtGOfB/uFQsAsabh1lAfXpIP5sQP7r8bFl+bwRRakmODDMMyj5PhG+f8u12Fx9i2AIL3nptdQSafSiXtdzq2IoAiwHAoXErCESgA7G2Z1Bim0Ifh3sbuTgbb0v6o46zOQW+XQG1P/bXumSTlDQD6l+e/jq0bXU+ZMMwx+V1YHl4rmLEw6X2yMSbKOhXF3P9FJAmz3oWuGTF3rEKRqDP4qPOST53wUoQMNlqYwjO9ccJb7z/ymlim6morKypXJZWt0rxtmATfgZD73R6/jZhfHUqQKshReqSPaHF18aAMyeI/GEJK2IsNwYgepnmhWx47siM8nP6NpmwcS6ADFDYlksrN5rGpjMlbEAOpXF+lIaIhbQ6mZtzGaV0bcSzQS1Jm2ied1fkOV31pqDUOV5fbSM255uNOSDch/Sih0Mv0d+MNiOD7gsCZRP42tz+UM86rMV26pRQ9cU1q2YW1y/qTP6mhAeXJDiSdn6yPMuzehdKqbb6G7hEcWOvycLwfq/5csGuBGNnC2jtb4fVTd52qroJ92b1PJnD/gwHUoAwentF+sDf3Jzo+6QgA4pRZCTkK3cQxEylFNEFNgQnISQqFm6qqX6wqOOAkIjOaB8BwqgMnKowMS6tHDGEEvu1uBK0Sp5sGzmR/xwu2qD
  template:
    metadata:
      name: minio-credentials
      namespace: recruitment
    type: Opaque
