---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: recruitment
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCx8GhgLmF/6Bz0iZt/xf89gt399h1QB+ULAyQJU5SRrx7TnDWgn9fn0vWRlbsTn7intFdibXtSm+2KLIJe50BxZZDmFD2MyuM/I1hl/E1A5sCvG2O+VPLV5vetKB7xr5dVZu7a7RMdU9prtagxn48nXW6+9mQhhBb8aWvycrqfCBZWRxArTSBRZLXPO48BwjaHOlefDldyNEW2ZwXzV7ihCPdpdU7gYjGHOvGuguVpNrjWB1oaTJFlyPsyU06R5eFFX4tghHBBYTm6zq+skVCmrTXvEnJDnSJi625GivWTGkTp7IwHgNKawQgCwcpQY+vdXHvg1cFB5qdBGs25wkNDxZNnrz+24gHlYVmj8yuqLUOI0TcwKv2q83VSbmA7V8BG/YylgvSD7JlDGrFt8cJcvFn+i6mriLfJa22pkbGJ6Q7/JeKRbiCw9gO3aYREX5xsuGXeDSbdXboPBVNexwRSHnbA7CZhQRScvIo+66bg9++TiNDVK53kHNkxtS+dQ9myGiUOzHjicNf/hehNYIM2/x1KJVNoR3RkyDa8Gi3nYFkZafmRkWgl/ye517LRrvVR2hGv6jO2At8Y+GqwnN54iIKkabFOPhmX6RoIGoGFdjhd9zElw0gc/RDp8hz87MrTbUHrljd/ZNB4noW9ONfUC7Ljg//JEUUV1gvnppihAoCQfhVMAdDKUwNi5fZ8q1V2f6WcXkrNxrad
    MINIO_ROOT_USER: AgBl7ZupCx/FbqJAUe8C7wN2X6ahd1VCYEa4U1Dpk9pz9XF9+t44P2jKAZNA5LUXPI3kUdr18xuRLwk1tkdXtNTy8B4xU7/MLi56J+HB9TaTscHYlERtrTCgtA2VeBqwaPCLlMx0PlbcDeyTk76qgFxjO1aanJsNqTeGCio9+9Rcu6ylxi+ilJ1uJyXa3qZ7ISC6lkdMvDoTbMZCtEbBaxRwu6A1++MlPNXeiHenE94MGIL7CqRmwj09/8B4DuL2ppWxe8TZbnQSbp1bol389uTADkq987RFABlmR3AJQcfI6ZgnT4ejUQ+U5FODVR9KMJGQQkuqMrQ5ysGFgotSlD+a+Dob7BHltfrS4a7KuJaXchFudYqIoKtmH3iWp8Obzffyz4VMoNNjjeyXQaM3cnbxNOiifS7yPCnZnJMU6qUggbeDP+x78K09mh7hQltAIOtNH+/iaMvZM+0BWjVVncxwX3pFUddDYCQ5BHFjL8ADIUeeOX4abKin7AzdcHfQw4DfXeFhccNi/CPvQw3S390Zz82kWrHNIvyJPAou+aBYV18i2311lJ9eqr0GOrt+q2N56HWD/5SEBR7QNX3lpKfHudfhH7lDuZxbBfaTt+wzZVSXIvl4OMSg5Ib+wW+MJIXIXOqHQQUysxywLWS1f/IbZNbiVnwUn9Y8mf64LYwGUxHtl8LDHkCsgfMEPruISfZP6hMcAzLjWFus
  template:
    metadata:
      name: minio-credentials
      namespace: recruitment
