---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    DB_PASSWORD: AgAg5yyz2BhcPN1EY9sh/wg3lvHNkiXrXO/BS729ktI+pYqM/EB/J7BIgJdN/rbI2y6Gv0FC/Lor7S9Q4lmdTkayhmnjtL4PuxwB8PtFxOl7OwW9xKOm1VCD60Pd0skoHg92jSTwVtLExFRMkX51Q0Wu5k3MPmPw9jwkA64effnHBWKgDxtP6POXzL6/z9aGAIE0UwIa/2eyC3HyvEpwarH0VXVm32VdF2vKlQ2XVPflqA5sTC1GDREW44P7eqr8HsjazIBTWGQSMFGg/CE78IySJWNshBalqFiYitH/dwn5fVcR5c0i4jHmHo+DOvCUYtdbumnut18QIQVPhSmdnExJzyAXaLwPXxwBfhQ568Q2nPqn//9xhROVq1mkkBGNSRMMp/61yCh8UppYU5v1K+7j1RMQbaz8mCmDVMYqejGd166/LtjZuZt3j4Z2X9ZstCejuA9q8/VWDS865+j2hLQTZDJBSrAlBIIbAJpBEF24MRZPLA+N3sJ0DrBjzf7zLmbCp+hxKgwMip9RP97lMufKAW3STUcAEvQtTf0k8CQ9x63Mz5wbEV2tAsCPrKczxqgWTqG+b3woY4+OgfMR9oDWdSsF/QhZ9o2QxER6pYvwDv9jHe+6M7CaZzOP4cYwlc8YXg2LeW/WM5tRGOHNOblALG8GLt4E/0cBcg21bER1jkIQIbdtv2q9NMjU8QpFzgFH0ufjkbkB/Q==
    DB_USERNAME: AgCucSC0M0kiptiERrtKzkOZeWhgnIrgOQiN228dqF1lC90RpG9kf8T3IjeWGaaNUKF6JVt/Lz087FAP0Yw+ydPkULF6IPIpR1+64O2SbE1JlqxSAbP5SpxfPwTupv1KXGfNYlyAYFlOlFRQolj37XtVNOqRIgWMvDksVcrOatHksd6/Xy++bcCMdIINbUuURs0VH4FUJUQYzLuEyI46MmCRbPMpX1dA81Ktq1IcwgosT4mUK0Y4pxSgJPcCEFhA8OG/YjDt2copmm9wvVWTUumMf6z70NrNpM4Eg2qhe5dfFAc+CQ7LHeU5oA87fYR7XkS2fCxknnMGCfVwyRnMOEEmzyDTUqrZAYaUdiv//IbvpHcqqGD+2cluY+McawDkKkeXPlX3+18bBx8wiqwR0HOmhGFOMlwFK6KVGWmcVAbwPVpahELG2dwUVV0BpJ78R3Thkt70WfRn+y6BB4VaOCowD2eQF1l3egJm5XAPTKCoZSyE0vv2IT4DxdCuv0e9FX/g0fiDuHjT/wj+YaFVkdq0xtreD0YoIvTPEl+Ll9y09e4Q6qiNwN3FlgVQheOghPFFVMVF2XEO8DQGGq9S/vGwIssGwglumKqxfgqCXA0hr+KnA3SmcgXFtlYs3PyQkmSlOWUrZ9AWRNqZn6icMweTgzZB8bZd3eMMCSjJctj2+sxX36BlJA6ax0O0vqHRr0dcS+vZAQ==
  template:
    metadata:
      name: notification-service-credentials
      namespace: recruitment
