---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workflow-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    FLOWABLE_DB_PASSWORD: AgAT2g41G+3ZNP1U/5TQ+MikcGSUxbN2j8ePsYDsXd5jHP2WrtdTp2bdcMlJmCPbY/58Q1nFHrZauB4X01cOAEx213oqMJRR4y8bY+Bd/U2UBQARnTbTw71vdNeSm5qSTPySMuEH13XFYqhVRrQQDjj15xCQPPDBYE2Me5vOuafbJYAc+cO8GxyZqvErZfc2f4gKd7HImOHUiVj7eXRwI86yjJJOBifqwgLaf3mP6gUgN6c6QxTrM82uaho0n2t82OPjxCGHIjtiCbBuUvjUEtufDGWURl3UQ7nKAxGSUIPx7Q2nH7qDspgVzovZUMk/z/4sjImw64sebN5amPom7DrVICTMpAF/eFl0JLisU46BAhpIX+lWQdkEGuZNesif++ap9kPEg2FZBTR9Y36a2wSE+lotQ7UpOOOW87olxlhEnJOAW2LHnfvngXQjpeZ2aXwdccwuCJdSH7cm4jhTLzxQhMivSOS4L8OsR7bBGls2//dHHvwFz1i3vCrgVL280eO9JaZwLlJwViqoACbZNkUKJsi3wpM5HRq+GRpuhhiWrtEvSx+x3M/0H76wvt/Z+uoJ5WfPCfC+2txstbBAhd8ZE1+hYCs7rEt1Cakc/ylJPfEGCK5tff3J1knFMaTKzncop2tSQuSyHoyK3BRmW03gHJzR9KDvj2ImsT9O9E/qpX1XCq+yHcZHF/PYntn7t+3SLcIWg9MpQw==
    FLOWABLE_DB_USERNAME: AgA3RYLlnHDTTTCREae6WJGXoNP8vNog1ITCW3yf73q8iNttpK0eURC6Ot010MNY4IMXeOEupupOa9mGW+fysg9hPOan1eZAACLqofvWs1yJeDhSKsKxyu4sYkLFTCx15FJ0Q+S9Q+CajmmYZ/SokRnRRxMFX46521lAs/CEAjGuFTug4/kwrbdWKBMSRTVeLAI54XdcawQ58810mToh0YMkRmdiSUFFFIF5IveGcTLghB2WY1jRTIictq2bORmpHIpgIcy2qtmutPk7y4o77UivXuCEe0/Vx4toi2FN/w2rnH4yl1N4mkf5ydRvpyoyMsPM9QVi0g5Tmutd3NBP6O9PQFY744urXdO//f1HGJ2KBmJkpSgvEVcSR9IPQNiY2vGMYzO/e2M9U8gHV+nWwcCr+vqSdmQ9D6GdwbRBVdhwynSR0EajWAJVZUqsEE03WHRv7wVI5mD0NtsTTyLE5syrL++mN7d0pSJaDULxgYmhB+fc+z4KjA2X2Swn7zzEl1mMIEfXskGv6GY6pl5PvZ0n1bwYBp6dbspWx6VFKi47938koz42eYIzMQsVTerqyhSmEAOUSIL5Cg/ojvTUwFj51LDPYsdFkOxPukUy4JImymQUKwk5BdDQU7OqbbFu9mryExYsdT9PGHOOAQbGzHVgtR+dwikpmBNSeDGmLLhQDw9NSSq1YFJPLIE4pn0BlR0b9KQDpgek7w==
  template:
    metadata:
      name: workflow-service-credentials
      namespace: recruitment
