fullnameOverride: application-service
replicas: 1
image:
  repository: ihab0/application-service
  tag: "4.5.0"
container:
  port: 8097
service:
  enabled: true
  type: ClusterIP
  port: 8097
probes:
  enabled: true
env:
  - name: SPRING_PROFILES_ACTIVE
    value: kube
  - name: CONFIG_SERVICE_URL
    value: http://config-service:9999
  - name: DISCOVERY_SERVICE_URL
    value: http://discovery-service:8761/eureka
  - name: KEYCLOAK_SERVER_URL
    value: http://keycloak-service:8080
  - name: KEYCLOAK_ISSUER_URI
    value: http://keycloak.localhost
  - name: KEYCLOAK_REALM
    value: micro-service
  - name: APP_DB_URL
    value: jdbc:postgresql://recruitment-db:5432/application_db
  - name: MINIO_URL
    value: http://minio:9000
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka:9092
secretEnv: []
existingSecret: application-service-credentials
existingSecretEnv:
  - name: MINIO_ACCESS_KEY
    key: MINIO_ACCES_KEY
serviceAccount:
  create: true
  automount: false
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
podDisruptionBudget:
  enabled: true
  minAvailable: 1
