apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recruitment-sealed-secrets
  namespace: argocd
spec:
  project: recruitment
  source:
    repoURL: https://github.com/recruitment-organisation/recruitment-gitops.git
    targetRevision: main
    path: .
    directory:
      recurse: false
      include: '*-credentials.sealed.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: recruitment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
