{{- if and .Values.secretEnv (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
{{- end }}
