---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgBiqxY6vho7NBB68VE2FR6Rjjsz/g9JJDzgJCchD09Gzu6HtS8HULps+g5jsPgfVZrZsuMS8QHT/qooDMYPNGQzNQVPOdYuxRsJuPkcRGixBv8OZaToNjYmeTmecoCLSXMswAr4GynwJ8cAbXD2rqVLMwzwPrp01+5tMkDJz9dMcDMyhgKRaDm0Oo3yH8sq2FTACR+q09xKUo7X0ZO4vNt1IU0msNYFNc0Udbz02OVtEf8trUl4vK084WIxaI0U9Sa1xVQHu1ZDO6qJuJvMIJkrXD2wQVdFMdGhYvFATdHQBhEZtVNUavxhMtwca/bZtelUTEDtc/y4YfIbeHKoBB2OF443TF7KKXv/svwvUTwrfHMNiGtpYHsLHwc/d4mgzcNCRR8tuF3r+1tinONrD7lwVz79SGBrQ7bwm5x0Uave6Nq9oipVz6O+stf1+9SH7UEpvnleYn7GJ0qU7LE46OnYGZnI7z3nHo65iC9N7CIP5h+RpM7OcYmRcElZOwU7JeYdPw2k46iDQC2UaKFvZveLaNhXbs8dAvjOfZxKxrFMZpvjI6AQskums/VMhyJPtKMqaJem07d0E03ROZxd6T6cL9t0XtPZfkKRRugEPg/cexB2JMv7uTRPmhkRfBqocFRPVxpAL8mG8h1CVEe8DdW6qpLCj5dNVipSWDYsj9cbZ1LhMA5NeK/kWGc7vzIyflJE5qAzww==
    KEYCLOAK_CLIENT_SECRET: AgCHqNllaMwE9n5oq8EpYfTArYkKqQcjrE/TxuxYK6DstAbSSl91iAGMPDNreZqdPOC3mCnAXiQoPzcUpZpdfaZEimeDLASGo2p+p/6WPX7Ze2Or3i/bv9c7d8G0aPSwQXO1IGgzYNWOFxqM72XfBjzgoMs9tCD2W7muI93DYmJdVCjZjtgchm2TBErd8D1ZtsuKs/Mg/E2DY4mEfpaWEQ3aWpZT+UcgQEMNQvsARrr8fnNESk0cHAUR+Vr3y28ZNAzpHqnkb3erZA4BO1vaRUxS30IXtgFrt58bnvBQFh58LgCk7iqhf7PMCnj68xHgVYKNeLClCsyqknDZwbaMY2ssCcvfBA5zENOHYXNT0uxjAKXCTFnaKhyB1cyLXdojZYVGhMsMG9tmJYOhoAcrs0F9GjRKu88MMw/3l2BCAQYK/GLkHeWsYf++tVs5I/7zAEt5IHYH5YJsQDH+0tbLFuclYetppbDYRqEwfPQF+JGEXjxP1X9mDO7YydghJQusxHLvXkaHSC94+Alk0FvxDlF9Jemzle+ZjCzmbzde9V6EFat7kDubj8gBQrpeOMWwoX69bp32NevuQIABtEqMtAKOcpjogbvbYQZ8sR99qlwnoIHGID+rOkI8x3Tfy2SqpNDTQxe9331WpotV0JUFK/7aarJ8HTVlgt3FWF87Umgj/2FMyK+5iFk5ng8D9NH9IeGwNsuXPGiY/Hx4A3selN0bfDrM5BcE3/1pd4hnS8sCJw==
  template:
    metadata:
      name: auth-service-credentials
      namespace: recruitment
