---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: job-offer-service-credentials
  namespace: recruitment
spec:
  encryptedData:
    JOB_OFFER_DB_PASSWORD: AgCMiZ6kJ3e4+VKV/DOh4S7BezE0D1bHbXHLch8aG+2qXnmVtMTR2ZfbTjMS5CWjWBqwMM//TEaA2kzScrdBeQ8g6J0IcBMn+UHotHXVAiii3sz0CKLHkQT/QES31Fk4pDbXWB+G+QX3TCNJQ87cRJ9dSjUoR1O/kw8uZizn5V6OgPO16+l9vSOFGqaVLsZ37V8h+BVlQqGoQyxGLTjOaAv/vHVeTGdjRYYd22oqoFJs6mZhFZvrSw0dmou++OoyOegMHx+lBGKuuts/XmQUx66xMP5ZEG/lsfnM8qDWuLEgFsl/UEVKhJ8Z00rMZ23Qq0t4XTO5K2mm16JlnqT63vWLmztrGkgWd/O27YvfkIiEI9TYAJBWzpAEBAcqkzpC7yAwRPkKUhoyjJcqDjJX6mzYwpcFDvW++s4B23VjYWAFYy1K/BSpUPgY/1s2qigxsUN6/3iBMFD11XlLI6hCBW2iifJy9MdBJyZ7TfFBWvBG13wNxCdp+sYFLW2fMS2tUWCu1phLPocxuJYwJjj9sxX3f31cQrkt+19mdS3Y1pBDgOu6SDRtB/enAr8ibPI+Yq04rek92Nhs62lyDcEr1zndyxRn4iHarkEnBHoHjjwfzSZP3LULV3Bvl5j+3S/OXikGl4iEPph7FbQNga5VMme4G9Jz7H6rOcSSzi1cvJYf//vTMFr0GJo/GIvAQvObyhyN8X0TQIrkNg==
    JOB_OFFER_DB_USERNAME: AgASOOmMaQhmX0SD3YV8pAdEw/Hp/dAHp00s5T2KEAa/a6LbY0PGdPkEQDLHIq/ww+1YdvmUepwt+2p/3XLY3Xa3DHvUxVRTeBq928MQQfUjQ/wKNPApj7poM+GTBHu2uEscrGuQPxmnE6bDG7jlon25W6M3UpE5nsUuT8jIeHsWtCYtUpv21TAIi69RnndtA16CNTl5jjXPWEdjuMkY1rnr8WaGD0KQKFxSHQI64e8DQ9XCMz1T6n7OAdfKmIt5ikFEU1T10AqDXai4wiWCfz3bmoHN/XrL0pNOlqZKqT0kL2YBqN4maQ4Wad6H+fJ8REGj5DXQvWDpxEDcx9DMXBVlKeyJe7D44AXKH67sHjVvwjeoaX394BAKW/uTtdP6TKlYlQEHnwbCtKnRbzhuU+ot+AtTgbdOsuncE7Pv0nuJeqXe/xcF9shjPOtcWpkUjJ3HYPpHhn/2HNSKjnPnnfVRaGYNP7FCqfskJJ4dR/ob6bn9kjbBFVYETEekBOpDSDYUeRNU4NpJM3IbvJNmUpcY94LLTQCBT9yUSkPvp6Qeak5nxcm5Uh0RQlfXViXgzckxR2U92JtsdcvCZqmNy3e5cm/GpTRxAu5GXzLo968vWrWj8IzTdzSZs+bW0DKtiXR4tiWydH8FYLWfcTnNZSQ+5CpgYXoqtiAgWpQXHmvY77mCVqiQWFuTnBPumg0nO0M+fF1krQ==
  template:
    metadata:
      name: job-offer-service-credentials
      namespace: recruitment
